name: Fusion
version: 1.5
main: fusion.main.Fusion
description: Creates the functions for KitPVP, including cosmetic features.
author: [Lemonbus]
authors: [xXkguyXx, Emperor_Koala]
softdepends: [MVdWPlaceholderAPI]